{{- if or .Values.server.env .Values.global.env -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "template.fullname" . }}-server
  labels:
    {{- include "template.labels" . | nindent 4 }}
    {{- include "template.server.selectorLabels" . | nindent 4 }}
data:
  {{- if .Values.global.env -}}
  {{- include "template.env" .Values.global | indent 2 }}
  {{- end -}}
  {{- if .Values.server.env -}}
  {{- include "template.env" .Values.server | indent 2 }}
  {{- end -}}
{{- end -}}
