apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "template.fullname" . }}-server
  labels:
    {{- include "template.labels" . | nindent 4 }}
    {{- include "template.server.selectorLabels" . | nindent 4 }}
spec:
  {{- if not .Values.server.autoscaling.enabled }}
  replicas: {{ .Values.server.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "template.server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.server.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "template.server.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.server.image.pullSecret }}
      imagePullSecrets:
        - name: "{{- .Values.server.image.pullSecret }}"
      {{- end }}
      serviceAccountName: {{ include "template.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.server.podSecurityContext | nindent 8 }}
      containers:
        - name: server
          securityContext:
            {{- toYaml .Values.server.securityContext | nindent 12 }}
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          envFrom:
            {{- if or .Values.global.env .Values.server.env }}
            - configMapRef:
                name: {{ include "template.fullname" . }}-server
            {{- end }}
            {{- if or .Values.global.secrets .Values.server.secrets }}
            - secretRef:
                name: {{ include "template.fullname" . }}-server
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.server.container.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
      {{- with .Values.server.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
