{{- if or .Values.server.secrets .Values.global.secrets -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "template.fullname" . }}-server
  labels:
    {{- include "template.labels" . | nindent 4 }}
    {{- include "template.server.selectorLabels" . | nindent 4 }}
data:
  {{- if .Values.global.secrets -}}
  {{- include "template.secret" .Values.global | indent 2 }}
  {{- end -}}
  {{- if .Values.server.secrets -}}
  {{- include "template.secret" .Values.server | indent 2 }}
  {{- end -}}
{{- end -}}
