{{- if or .Values.client.secrets .Values.global.secrets -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "template.client.fullname" . }}
  labels: {{- include "template.client.labels" . | nindent 4 }}
  name: {{ include "template.fullname" . }}-client
  labels:
    {{- include "template.labels" . | nindent 4 }}
    {{- include "template.client.selectorLabels" . | nindent 4 }}
data:
  {{- if .Values.global.secrets -}}
  {{- include "template.secret" .Values.global | indent 2 }}
  {{- end -}}
  {{- if .Values.client.secrets -}}
  {{- include "template.secret" .Values.client | indent 2 }}
  {{- end -}}
{{- end -}}
