services:
  server:
    image: tuto-monorepo/server:dev
    container_name: tuto-monorepo_server
    build:
      context: ../apps/server
      dockerfile: ./Dockerfile
      target: dev
    restart: always
    ports:
      - 8081:8081
    volumes:
      - ../apps/server:/app
      - /app/node_modules
    networks:
      - tuto-monorepo-network

  client:
    image: tuto-monorepo/client:dev
    container_name: tuto-monorepo_client
    build:
      context: ../apps/client
      dockerfile: ./Dockerfile
      target: dev
    restart: always
    ports:
      - 8080:8080
    environment:
      VITE_SERVER_HOST: http://localhost:8081
    volumes:
      - ../apps/client:/app
      - /app/node_modules
    networks:
      - tuto-monorepo-network

networks:
  tuto-monorepo-network:
    driver: bridge