services:
  server:
    image: tuto-monorepo/server:prod
    container_name: tuto-monorepo_server
    build:
      context: ../apps/server
      dockerfile: ./Dockerfile
      target: prod
    restart: always
    ports:
      - 8081:8081
    networks:
      - tuto-monorepo-network

  client:
    image: tuto-monorepo/client:prod
    container_name: tuto-monorepo_client
    build:
      context: ../apps/client
      dockerfile: ./Dockerfile
      target: prod
    restart: always
    ports:
      - 8080:8080
    environment:
      VITE_SERVER_HOST: http://localhost:8081
    networks:
      - tuto-monorepo-network

networks:
  tuto-monorepo-network:
    driver: bridge