{{- if .Values.vso.enabled -}}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: foo-secrets
spec:
  vaultAuthRef: vault-auth
  mount: mi-tobi
  path: foo
  type: kv-v2
  destination:
    name: foo-secrets
    create: true
{{- end -}}
